package com.meetloggerv2.core.theme

object AppStrings {
    const val APP_NAME = "MeetLogger"
    const val APP_SLOGAN = "See what\nhappened…\nAudio Unfold,\nDocuments Untold."
    const val DEFAULT_WEB_CLIENT_ID = "687079496758-sikpp68be4qbgba37pfuf2slrdjn1j7c.apps.googleusercontent.com"
    const val SUMMARIZED_FILES = "Summarized Files"
    const val SELECT_ALL = "Select All"
    const val DIALOG_CANCEL = "Cancel"
    const val DIALOG_PROCEED = "Proceed"
    const val DIALOG_SAVE = "Save"
    const val DIALOG_DELETE = "Delete"
    const val DIALOG_OVERWRITE = "Overwrite"
    const val DIALOG_NEW_COPY = "New Copy"
    const val DIALOG_TITLE_COPY_REPORT = "Copy File"
    const val DIALOG_TITLE_CHOOSE_LANGUAGE = "CHOOSE LANGUAGE"
    const val DIALOG_TITLE_WARNING = "WARNING"
    const val MSG_DELETE_SELECTED_REPORTS = "Delete selected reports?"
    const val MSG_DELETE_SELECTED_AUDIO = "Delete selected?"
    const val EMPTY_HOME_SEARCH_MESSAGE = "No documents match your search."
    const val EMPTY_REPORT_SEARCH_MESSAGE = "No summaries found matching your search."
    const val ERROR_NAME_EMPTY = "Name cannot be empty"
    const val MSG_DOWNLOADED_SUCCESS = "Downloaded successfully"
    const val TOAST_PASSWORD_RESET_SENT = "Password reset email sent."
    const val ERROR_PASSWORDS_DO_NOT_MATCH = "Passwords do not match"
    const val ERROR_NAME_REQUIRED = "Please enter your full name"
    const val ERROR_PASSWORD_RULES = "Password must be at least 8 characters long and contain uppercase, lowercase, digit, and special character"
    const val BTN_GET_STARTED = "Get Started"
    const val DIALOG_YES = "Yes"
    const val DIALOG_NO = "No"
    const val DIALOG_LANGUAGE_SWITCH_MSG = "Select the translation target language for this document"
}
